//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team:.
        /// </summary>
        public static string away_team {
            get {
                return ResourceManager.GetString("away_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string captain {
            get {
                return ResourceManager.GetString("captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string goals_scored {
            get {
                return ResourceManager.GetString("goals_scored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team:.
        /// </summary>
        public static string home_team {
            get {
                return ResourceManager.GetString("home_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string info_country {
            get {
                return ResourceManager.GetString("info_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string info_draws {
            get {
                return ResourceManager.GetString("info_draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string info_games_played {
            get {
                return ResourceManager.GetString("info_games_played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals against:.
        /// </summary>
        public static string info_goals_against {
            get {
                return ResourceManager.GetString("info_goals_against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Differential: .
        /// </summary>
        public static string info_goals_diff {
            get {
                return ResourceManager.GetString("info_goals_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for:.
        /// </summary>
        public static string info_goals_for {
            get {
                return ResourceManager.GetString("info_goals_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string info_losses {
            get {
                return ResourceManager.GetString("info_losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string info_points {
            get {
                return ResourceManager.GetString("info_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string info_wins {
            get {
                return ResourceManager.GetString("info_wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches available for these teams.
        /// </summary>
        public static string no_matches_available {
            get {
                return ResourceManager.GetString("no_matches_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string not_available {
            get {
                return ResourceManager.GetString("not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string setting_confirm {
            get {
                return ResourceManager.GetString("setting_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string setting_gender {
            get {
                return ResourceManager.GetString("setting_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string setting_language {
            get {
                return ResourceManager.GetString("setting_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository type:.
        /// </summary>
        public static string setting_repo {
            get {
                return ResourceManager.GetString("setting_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window mode:.
        /// </summary>
        public static string setting_window_mode {
            get {
                return ResourceManager.GetString("setting_window_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings:.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards: .
        /// </summary>
        public static string yellow_cards {
            get {
                return ResourceManager.GetString("yellow_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
